services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: my-backend-container
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: my-frontend-container
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
